config/routes.rb
Rails.application.routes.draw do
  root to: "forum/posts#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :api do
    namespace :v1 do
      namespace :blog do
        resources :posts do
          resources :comments
        end
      end

      namespace :forum do
        resources :posts do
          resources :comments
        end
      end
    end
  end

  namespace :blog do
    resources :posts do
      resources :comments
    end
  end

  namespace :forum do
    resources :posts do
      resources :comments
    end
  end

  resources :users

  resources :posts do
    resources :comments
  end

end

app/models/blog/post.rb
class Blog::Post < Post
  default_scope { where(platform: "blog") }
end

app/models/forum/post.rb
class Forum::Post < Post
  default_scope { where(platform: "forum") }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user

  def content_html
    MarkdownRender.new(text: content).render
  end
end

app/controllers/api/v1/blog/posts_controller.rb
class Api::V1::Blog::PostsController < Api::V1::ApiController
  def index
    
  end
end

app/controllers/api/v1/forum/posts_controller.rb
class Api::V1::Forum::PostsController < Api::V1::ApiController
  def index
    
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  def index
    
  end
end

app/controllers/forum/posts_controller.rb
class Forum::PostsController < ApplicationController
  def index
    @posts = Forum::Post.includes(:user).all
  end

  def show
    @post = Forum::Post.find(params[:id])
    @comments = @post.comments.includes(:user)

    gon.push(
      post: {
        id: @post.id
      }
    )
  end

  def new
    if not current_user
      redirect_to new_user_session_path(nil, s: 1, r: URI(request.referer).path)
    end
    @post = Forum::Post.new
  end

  def create
    post = Forum::Post.new(post_params)
    post.user = current_user

    status = post.save ? 1 : 0

    render json: { status: status, post: { id: post.id } }
  end

  def edit
    
  end

  def update
    
  end

  def delete
    
  end

  private

    def post_params
      params.permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/forum/posts/index.html.erb
<h2 class="page-title">討論區</h2>

<a href="<%= new_forum_post_path %>">
  <div class="editor-btn-md">
    <i class="fa fa-plus" aria-hidden="true"></i>
    <span>發表文章</span>
  </div>
</a>

<%= render "posts/posts" %>

app/views/forum/posts/new.html.erb
<link href="https://cdn.quilljs.com/1.3.1/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.3.1/quill.js"></script>
<%= javascript_include_tag "forum/posts/new" %>

<%= render "layouts/container" do %>

  <div class="spacer"></div>

  <h2>發表新文章</h2>

  <div class="spacer"></div>

  <%= form_for @post do |f| %>
    <div class="editor">
      <%= f.text_field :title, class: "new-post-title", placeholder: "標題" %>

      <div class="spacer"></div>

      <div id="editor" class="editor-full"></div>

      <div class="editor-save">
        <span class="editor-save-text">儲存</span>
        <img src="<%= image_url("loading-small.gif") %>" alt="" class="loading hidden" />
      </div>
      <div class="editor-cancel">
        <span class="editor-cancel-text">取消</span>
      </div>

    </div>
  <% end %>
<% end %>

app/views/forum/posts/show.html.erb
<%= javascript_include_tag "forum/posts/show" %>

<%= render "layouts/container" do %>
  <%= render "posts/post", post: @post %>
<% end %>

<%= render "layouts/container" do %>
  <div class="spacer" />

  <div class="edit-btn">
    <i class="fa fa-comment-o" aria-hidden="true"></i>
    <span>回覆</span>
  </div>
  <div class="editor-container hidden">
    <%= render "components/editor" %>
  </div>

  <div class="spacer" />
  <%= render "comments/comments", comments: @comments %>
<% end %>