config/routes.rb
Rails.application.routes.draw do
  root to: "forum/posts#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :api do
    namespace :v1 do
      namespace :blog do
        resources :posts do
          resources :comments
        end
      end

      namespace :forum do
        resources :posts do
          resources :comments
        end
      end
    end
  end

  namespace :blog do
    resources :posts do
      resources :comments
    end
  end

  namespace :forum do
    resources :posts do
      resources :comments
    end
  end

  resources :users

  resources :posts do
    resources :comments
  end

end

app/models/blog/post.rb
class Blog::Post < Post
  default_scope { where(platform: "blog") }
end

app/models/forum/post.rb
class Forum::Post < Post
  default_scope { where(platform: "forum") }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user

  def content_html
    MarkdownRender.new(text: content).render
  end
end

app/controllers/api/v1/blog/posts_controller.rb
class Api::V1::Blog::PostsController < Api::V1::ApiController
  def index
    
  end
end

app/controllers/api/v1/forum/posts_controller.rb
class Api::V1::Forum::PostsController < Api::V1::ApiController
  def index
    
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  def index
    
  end
end

app/controllers/forum/posts_controller.rb
class Forum::PostsController < ApplicationController
  def index
    @posts = Forum::Post.includes(:user).all
  end

  def show
    @post = Forum::Post.find(params[:id])
    @comments = @post.comments.includes(:user)

    gon.push(
      post: {
        id: @post.id
      }
    )
  end

  def new
    if not current_user
      redirect_to new_user_session_path(nil, s: 1, r: URI(request.referer).path)
    end
    @post = Forum::Post.new
  end

  def create
    post = Forum::Post.new(post_params)
    post.user = current_user

    status = post.save ? 1 : 0

    render json: { status: status, post: { id: post.id } }
  end

  def edit
    
  end

  def update
    
  end

  def delete
    
  end

  private

    def post_params
      params.permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="single-post">
  <div class="title">
    <h2><%= post.title %></h2>
  </div>

  <div class="author">
    <a href="<%= user_path(post.user) %>">
      <%= post.user.fullname %>
    </a>
  </div>
  <span class="datetime">
    <%= post.created_at.strftime("%Y-%m-%d") %>
  </span>

  <hr />
  <div class="content">
    <%=raw post.content_html %>
  </div>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <div class="post-column">
    <div class="sidebar">
      
    </div>
    <div class="content">
      <div class="title">
        <a href="<%= forum_post_path(post) %>">
          <%= truncate(post.title, length: 30, omission: '...') %>
        </a>
      </div>
      
      <div class="author">
        <a href="<%= user_path(post.user) %>">
          <%= post.user.fullname %>
        </a>
      </div>

      <div class="datetime">
        <%= distance_of_time_in_words(Time.now, post.created_at, scope: 'datetime.distance_in_words.short') %>
      </div>
    </div>
  </div>
<% end %>